[RECORDING]
# [Hz]. sampling rate.
SAMPLE_RATE=48000  
# [sec]. duration recording audio.               
RECORD_SEC=10                     

[NOTIFICATIONS]
# method for sending notifications, 0=windows 1=xso
NOTIFICATION_METHOD=1
# [sec]. duration notification popup stays.           
NOTIFICATION_DURATION=5       

[OSC]
PORT=9001
IP=localhost
PARAMETER_NAME=SongSearch